title: Kristen Fussner
description: My Personal Blog
author: Kristen Fussner
logo: /assets/media/avatar.png
github: https://github.com/kristenfussner
about: Catholic mom of 2 beautiful girls

baseurl: ""
url: "http://kristen.fussner.us"

disqus_shortname: kenfussner
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]