# Site settings
title: Kristen Fussner
name: Kristen Fussner
email: kristen@fussner.us
description: >
    A humble Catholic mom
baseurl: "http://kristen.fussner.us" # the subpath of your site, e.g. /blog
url: "http://kristen.fussner.us" # the base hostname & protocol for your site
twitter_username: kristenfussner # your Twitter username
github_username: kristenfussner # your Github username
disqus_username: kristenfussner # your disqus username

#google-analytics: UA-75034651-1 # add it if you have one

# Build settings
permalink: pretty
markdown: kramdown
